name: Pull Request

on: pull_request

env:
  DOTNET_NOLOGO: true

jobs:

  build_and_test_debug:
    name: Build and Test (DEBUG)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - run: dotnet restore --verbosity minimal

      - run: dotnet build --configuration Debug /p:ContinuousIntegrationBuild=true

      - run: dotnet test --configuration Debug --verbosity minimal --no-build --collect:"XPlat Code Coverage" --results-directory "./.codecoverage"

      - name: Code coverage
        uses: codecov/codecov-action@v3
        with:
          directory: "./.codecoverage"
          fail_ci_if_error: true

  build_test_pack_release:
    name: Build, Test and Pack (RELEASE)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build version prefix/suffix
        run: |
          echo "VERSION_PREFIX=$(( 100 + ${{ github.run_number }} )).0.0" >> $GITHUB_ENV
          echo "VERSION_SUFFIX=alpha" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - run: dotnet restore --verbosity minimal

      - run: dotnet build --configuration Release -p:ContinuousIntegrationBuild=true -p:DebugType=Embedded -p:VersionPrefix=$VERSION_PREFIX --version-suffix $VERSION_SUFFIX

      - run: dotnet test --configuration Release --no-build

      - run: dotnet pack --configuration Release --no-build --output ./artifacts -p:DebugType=Embedded -p:VersionPrefix=$VERSION_PREFIX --version-suffix $VERSION_SUFFIX

      - name: Publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: NuGetPackage.${{ env.VERSION_PREFIX }}-${{ env.VERSION_SUFFIX }}
          path: ./artifacts/
